best = {
    "storage_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "storage_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "storage_embedding_model": "nomic-ai/nomic-embed-text-v1",
    "storage_collection_space": "cosine",
    "storage_asr_chunk_size": 5000,
    "storage_asr_overlap": 500,
    "storage_asr_whisper_model_name": "medium.en",
    "storage_asr_postprocessing_fn": "",
    "storage_ocr_chunk_size": 2500,
    "storage_ocr_overlap": 750,
    "storage_ocr_capture_every_n_s": 45,
    "storage_ocr_frame_diff_threshold": 60,
    "storage_ocr_library": "easyocr",
    "storage_ocr_postprocessing_fn": "",
    "storage_ocr_llm_preprompt": "",
    "storage_average_asr_ocr": False,
    "retriever_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "retriever_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "retriever_reranker_model_name": "mixedbread-ai/mxbai-rerank-large-v1",
    "retriever_reranker_n_docs": 40,
    "retriever_n_docs": 8,
    "retriever_modalities_overwrite": "",
    "retriever_distance_threshold": 0.8,
    "retriever_context_preparation_scheme": "",
    "generator_llm_model_name": "Mistral 7B Instruct v0.2 Q5_K_M",
    "generator_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "generator_preprompt": "Given the context, answer the question.",
    "generator_max_tokens": 2048,
    "generator_temperature": 0.0,
}

second_best = {
    "storage_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "storage_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "storage_embedding_model": "nomic-ai/nomic-embed-text-v1",
    "storage_collection_space": "cosine",
    "storage_asr_chunk_size": 5000,
    "storage_asr_overlap": 500,
    "storage_asr_whisper_model_name": "tiny.en",
    "storage_asr_postprocessing_fn": "",
    "storage_ocr_chunk_size": 3000,
    "storage_ocr_overlap": 300,
    "storage_ocr_capture_every_n_s": 30,
    "storage_ocr_frame_diff_threshold": 60,
    "storage_ocr_library": "easyocr",
    "storage_ocr_postprocessing_fn": "",
    "storage_ocr_llm_preprompt": "",
    "storage_average_asr_ocr": False,
    "retriever_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "retriever_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "retriever_reranker_model_name": "mixedbread-ai/mxbai-rerank-large-v1",
    "retriever_reranker_n_docs": 30,
    "retriever_n_docs": 5,
    "retriever_modalities_overwrite": "",
    "retriever_distance_threshold": 0.8,
    "retriever_context_preparation_scheme": "llm_filter_relevant",
    "generator_llm_model_name": "Mistral 7B Instruct v0.2 Q5_K_M",
    "generator_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "generator_preprompt": "Given the context, answer the question. You MUST use the information provided in the context.",
    "generator_max_tokens": 2048,
    "generator_temperature": 0.0,
}

merge = {
    "storage_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "storage_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "storage_embedding_model": "nomic-ai/nomic-embed-text-v1",
    "storage_collection_space": "cosine",
    "storage_asr_chunk_size": 5000,
    "storage_asr_overlap": 500,
    "storage_asr_whisper_model_name": "tiny.en",
    "storage_asr_postprocessing_fn": "",
    "storage_ocr_chunk_size": 2500,
    "storage_ocr_overlap": 750,
    "storage_ocr_capture_every_n_s": 30,
    "storage_ocr_frame_diff_threshold": 60,
    "storage_ocr_library": "easyocr",
    "storage_ocr_postprocessing_fn": "",
    "storage_ocr_llm_preprompt": "",
    "storage_average_asr_ocr": False,
    "retriever_llm_model_name": "Llama 3 8B Instruct Nous Q5_K_M",
    "retriever_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "retriever_reranker_model_name": "mixedbread-ai/mxbai-rerank-large-v1",
    "retriever_reranker_n_docs": 30,
    "retriever_n_docs": 5,
    "retriever_modalities_overwrite": "",
    "retriever_distance_threshold": 0.8,
    "retriever_context_preparation_scheme": "llm_filter_relevant",
    "generator_llm_model_name": "Mistral 7B Instruct v0.2 Q5_K_M",
    "generator_llm_system_message": "You are an AI assistant that follows instruction extremely well. Help as much as you can.",
    "generator_preprompt": "Given the context, answer the question. You MUST use the information provided in the context.",
    "generator_max_tokens": 2048,
    "generator_temperature": 0.0,
}
